config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/pages/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/newc', to: 'courses#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :messages # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :courses

  resources :courses do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:new, :create, :destroy]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base

  attr_accessible :email, :name, :docente, :password, :password_confirmation

  # basically, the method realizes the authentication system
  has_secure_password

  # each user can have some posts associated and they must be destroyed together with the user
  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  # each user can have many relationships
  # we need to explicitly define a foreign key since, otherwise, Rails looks for a relationship_id column (that not exists)
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy

  # each user can have many followed users, through the relationships table
  # since followed_users does not exist, we need to give to Rails the right column name in the relationships column (with source: "followed_id")
  has_many :followed_users, through: :relationships, source: :followed

  # each user can have many "reverse" relationships (by inverse reading the Relationship model)
  has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy

  # each user can have many followers, through reverse relationships
  has_many :followers, through: :reverse_relationships

  # put the email in downcase before saving the user
  before_save { |user| user.email = email.downcase }
  # call the create_remember_token private method before saving the user
  before_save :create_remember_token

  # name must be always present and with a maximum length of 50 chars
  validates :name, presence: true, length: { maximum: 50 };

  Valid = /^docente|studente/i

  validates :docente, presence: true, format: { with: Valid }


  # each user can send/receive some private messages (thanks to the simple-private-messages gem)
  has_private_messages

  # email allowed format representation (expressed as a regex)
  VALID_EMAIL_REGEX = /^s[0-9.]|[a-z.]\.[a-z.]+@studenti.polito.it|polito.it/i

  # email must be always present, unique and with a specific format
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  # password must be always present, and with a minimum length of 6 chars
  validates :password, presence: true, length: { minimum: 6 }

  # password_confirmation must be always present
  validates :password_confirmation, presence: true

  # is the current user following the given user?
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  # follow a give user
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  # unfollow a given user
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  # get the post to show in the wall
  def feed
    Post.from_users_followed_by(self)
  end

  # get the searched user(s) by (part of her) name
  def self.search(user_name)
    if user_name
      where('name LIKE ?', "%#{user_name}%")
    else
      scoped # return an empty result set
    end
  end

  # private methods
  private

    def create_remember_token
      # create a random string, safe for use in URIs and cookies, for the user remember token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # check if the user is logged in (e.g., for editing only his information)
  before_filter :signed_in_user, only: [:edit, :update, :index, :destroy, :messages]
  # check if the current user is the correct user (e.g., for editing only his information)
  before_filter :correct_user, only: [:edit, :update, :messages]
  # check if the current user is also an admin
  before_filter :admin_user, only: :destroy

  def show
    # get the user with id :id
    @user = User.find(params[:id])

    # get and paginate the posts associated to the specified user
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
    # init the user variable to be used in the sign up form
    @user = User.new
  end

  def create
    # refine the user variable content with the data passed by the sign up form
    @user = User.new(params[:user])
    if @user.save
      # handle a successful save
      flash[:success] = 'Welcome to PoliTo!'
      # automatically sign in
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    # intentionally left empty since the correct_user method (called by before_filter) initialize the @user object
    # without the correct_user method, this action should contain:
    # @user = User.find(params[:id])
  end

  def update
    # intentionally left empty since the correct_user method (called by before_filter) initialize the @user object
    # without the correct_user method, this action should also contain:
    # @user = User.find(params[:id])
    # check if the update was successfully
    if @user.update_attributes(params[:user])
      # handle a successful update
      flash[:success] = 'Profile updated'
      # re-login the user
      sign_in @user
      # go to the user profile
      redirect_to @user
    else
      # handle a failed update
      render 'edit'
    end
  end

  def index
    # get all the users from the database - without pagination
    # @users = User.all
    @usere = User.where(:docente => "docente" )
    # get all the users from the database - with pagination
    if @usere == 'docente'
    @usere = User.paginate(page: params[:page])
    else
    @users = User.paginate(page: params[:page])
      end
  end

  def destroy
    # delete the user starting from her id
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted!'
    redirect_to users_url
  end

  # Actions to list the followed users and the followers of a user
  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  # Paginated search for users
  def search
    @users = User.search(params[:search]).paginate(page: params[:page])
  end

  # Paginate message index
  def messages
    # with the current restrictions, user is always the current_user
    @user = User.find(params[:id])
    @messages = @user.received_messages.paginate(page: params[:page])
  end


  private

    # Take the current user information (id) and redirect her to the home page if she is not the 'right' user
    def correct_user
      # init the user object to be used in the edit and update actions
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user) # the current_user?(user) method is defined in the SessionsHelper
    end

    # Redirect the user to the home page is she is not an admin (e.g., if the user cannot perform an admin-only operation)
    def admin_user
      redirect_to root_path unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Return the Gravatar (http://gravatar.com) for a given user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_follow.html.erb
<% # linked to the create action in the Relationship controller %>
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <% # the hidden field contains the information needed for following a user %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit 'Follow', class: 'btn btn-large btn-default' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_search_form.html.erb
<% # form_tag is equivalent to form_for, but it is used for generic form, without a model behind
    # a search form always uses a GET method %>
<%= form_tag search_users_path, method: 'get', class: 'navbar-search pull-left' do %>
    <% # text_field_tag: the first parameter is the id/name of the input tag; the second is the value of the tag %>
    <%= text_field_tag :search, params[:search], class: 'search-query', placeholder: 'Search' %>
<% end %>

app/views/users/_unfollow.html.erb
<% # linked to the destroy action in the Relationship controller %>
<%= form_for(current_user.relationships.find_by_followed_id(@user), html: { method: :delete }, remote: true ) do |f| %>
  <%= f.submit 'Unfollow', class: 'btn btn-large-default' %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      <% # since browsers cannot send DELETE request, Rails fakes them with javascript... %>
      | <%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Edit user' %>

<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit 'Save changes', class: 'btn btn-large btn-default' %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">Change</a>
  </div>
</div>

app/views/users/index.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'All Users' %>

<h1>All users</h1>
<%= will_paginate %>

<ul class="users">
  <h2>Teachers</h2>

  <%= render @usere %>
</ul>

<ul class="users">
  <h2>Students</h2>
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/messages.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Messages' %>

<h1>Received messages</h1>

<%= will_paginate @messages %>

<ul class="messages">
  <%= render @messages %>
</ul>

<%= will_paginate @messages %>

app/views/users/new.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Sign Up' %>

<h1>Sign Up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :docente, 'Che tipo di utente sei? (docente/studente)' %>
        <%= f.text_field :docente %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit 'Create my account', class: 'btn btn-large btn-default' %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Search results' %>

<h1><%= page_entries_info @users %></h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, @user.name %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <% if current_user.following?(@user) %>
        <section>
          <%= link_to 'New message', new_message_path(user: @user.id), role: 'button', class: 'btn btn-info', remote: true %>
          <div class="message"></div>
        </section>
    <% end %>
  </aside>

  <div class="span8">

    <%= render 'follow_form' if signed_in? %>
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <% # since we are in a Users view, we need to specify that the pagination is for the posts %>
      <% will_paginate @posts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to 'View my profile', @user %></span>
      <span><b>Posts:</b> <%= @user.posts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>