config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/pages/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/newc', to: 'courses#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :messages # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :courses

  resources :courses do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:new, :create, :destroy]

end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="row">
      <div class="field span7">
        <%= f.text_area :content, placeholder: 'Write a comment' %>
      </div>
      <div class="span2">
        <%= f.submit 'Post', class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% # handle and show forms errors %>
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li>* <%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <% # we need to write in this way the partial rendering for passing the collection %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content">
    <%= feed_item.content %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago
  </span>
</li>

app/views/shared/_message_form.html.erb
<div id="newMessage" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h4>A message for <%= @user.name %></h4>
  </div>
  <div class="modal-body">
    <%= form_for(@message) do |f| %>
        <div class="field">
          <%= f.hidden_field :sender, value: current_user.id %>
          <%= f.hidden_field :recipient, value: @user.id %>

          <%= f.label :subject %>
          <%= f.text_field :subject, value: @message.subject %>

          <%= f.label :body %>
          <%= f.text_area :body %>
        </div>
  </div>
        <div class="modal-footer">
          <%= f.submit 'Send', class: 'btn btn-primary' %>
        </div>

    <% end %>
</div>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="row">
    <div class="field span7">
      <%= f.text_area :content, placeholder: 'What are you doing?' %>
    </div>
    <div class="span2">
      <%= f.submit 'Post', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% # we are going to use this partial in the home and in the user profile;
   # in the home @user is nil and needs to be filled %>
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
     following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
     followers
  </a>
  <% if current_user?(@user) %>
      <a href="<%= messages_user_path(@user) %>">
        <strong id="unread_messages" class="stat">
          <%= @user.unread_message_count %>
        </strong>
        messages
      </a>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<% # current user gravatar %>
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>

<% # current user name, link to her profile and her posts number %>
<h1><%= current_user.name %></h1>
<span><%= link_to 'View my profile', current_user %></span>
<span><%= pluralize(current_user.posts.count, 'post') %></span>