config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/pages/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/newc', to: 'courses#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :messages # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :courses

  resources :courses do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:new, :create, :destroy]

end

app/views/pages/about.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'About' %>

<h1>About</h1>
<p>Questo è il social network per il sito della didattica!</p>

app/views/pages/contact.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Contact' %>

<h1>Contact</h1>
<p>Veronica Pala</p>

app/views/pages/faq.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Faq' %>

<h1>Faq</h1>
<p>Domande frequenti...</p>

app/views/pages/home.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Home' %>

<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <% if teacher? %>
            <%= link_to 'New Course', newc_path, class: 'btn btn-large btn-default' %>
        <% end %>
      </section>
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="span8">
      <%= render 'shared/post_form' %>
      <h3>Wall</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>
        Benvenuto al Poli!!!!
    </h1>
    <h2>
        Registrati o fai il login per entrare nel sito!
    </h2>
    <%= link_to 'Sign up now!', signup_path, class: 'btn btn-large btn-default' %>
  </div>
<% end %>