config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/pages/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/newc', to: 'courses#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :messages # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :courses

  resources :courses do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://didattica.polito.it/" > News </a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "PoliTo", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% #link_to is the Rails helper to create links (it generates <a...> tags) %>
          <li><%=link_to "Home",    root_path %></li>
          <li><%=link_to "Faq",     faq_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Courses", courses_path %></li>
            <li><%= render 'users/search_form' %></li>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                </ul>
            </li>
            <% else %>
                <li><%=link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://htmlshim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <% # method to automatically prevent Cross-Site Request Forgery %>
  <%= csrf_meta_tags %>
  <% # partial for the HTML shim %>
  <%= render 'layouts/shim'%>
</head>
<body>
  <% # partial for the header %>
  <%= render 'layouts/header' %>
  <div class="container">
    <% # the flash message; it supports different type of communications %>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <% # partial for the footer %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>